version: '3.8'
services:
  vary:
    image: alphia/vary-runtime:v1
    command: ["flask --app /workspace/Vary-toy/Vary-master/vary/demo/run_web_service.py run --host '0.0.0.0' --port '8080'"]
    depends_on:
      - minio
    restart: unless-stopped
    volumes:
      - ./workspace:/workspace
      - ./runpod-volume:/runpod-volume
    ports:
      - '10022:22'
      - '18080:8080'
    environment:
      PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINhnX1OHpedZcA/cHvGINxTKsR5NE1qfTFDSS1CaEk9h alphia@163.com"
      JUPYTER_PASSWORD: "Mgq789rBptney8eF"
      HTTP_PROXY: "http://192.168.188.27:7890"
      HTTPS_PROXY: "http://192.168.188.27:7890"
      ALL_PROXY: "socks5://192.168.188.27:7890"
      NO_PROXY: "*.xjtu.edu.cn,*.cn,localhost,192.168.0.0/16,127.0.0.1,172.18.0.0/16,172.17.0.0/16,172.0.0.0/8"
    networks:
      - app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
  minio:
    image: bitnami/minio:latest
    restart: unless-stopped
    volumes:
      - /home/hegang/minio-data:/bitnami/minio/data
    ports:
      - '9001:9001'
    networks:
      - app
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app
  ppt-structure-svc:
    image: alphia/ppt-structure-svc:v5
    restart: unless-stopped
    ports:
      - '18000:18000'
    depends_on:
      - rabbitmq
      - minio
    networks:
      - app
  caption-msg-consumer:
    image: alphia/caption-message-consumer:v5
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - minio
    networks:
      - app

networks:
  app:
   name: app