version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  vary:
    image: alphia/vary-runtime:v3
    command: /bin/bash -c "cd /workspace/Vary-toy/Vary-master/; export PYTHONPATH=\"${PYTHONPATH}:/workspace/Vary-toy/Vary-master\"; flask --app vary/demo/run_web_service.py run --host=0.0.0.0 --port=18080"
    depends_on:
      - minio
    restart: unless-stopped
    volumes:
      - /home/hegang/workspace:/workspace
      - /home/hegang/runpod-volume:/runpod-volume
      - /home/hegang/workspace/cache:/cache
    ports:
      - '10022:22'
      - '18080:18080'
    environment:
      PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINhnX1OHpedZcA/cHvGINxTKsR5NE1qfTFDSS1CaEk9h alphia@163.com"
      JUPYTER_PASSWORD: "Mgq789rBptney8eF"
    networks:
      - app-tier
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
  minio:
    image: bitnami/minio:latest
    restart: unless-stopped
    volumes:
      - /home/hegang/minio-data:/bitnami/minio/data
    ports:
      - '9001:9001'
      - '9000:9000'
    networks:
      - app-tier
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-tier
  ppt-structure-svc:
    image: alphia/ppt-structure-service:v5
    restart: unless-stopped
    ports:
      - '18000:18000'
    depends_on:
      - rabbitmq
      - minio
    networks:
      - app-tier
  caption-msg-consumer:
    image: alphia/caption-message-consumer:v13
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - minio
    networks:
      - app-tier